### ISSUE TITLE
Rename with_something

### ISSUE THREAD

**Issue by krlmlr** [jimhester/withr#10]
It's not really a `with` function, more a constructor. How about `make_with`?

**Comment by jimhester** [comment]
Maybe it can just be `with_`, 
```r
with_(setwd)("..", getwd())
# "/home/jhester/Dropbox/projects/withr"
```

**Comment by krlmlr** [comment]
This pattern has different semantics in the Hadleyverse ;-)

If you don't like the `make_` prefix, how about `create_with_fun`?

I see the idea: `with_dir` and `with_(setwd)` are essentially the same. For those who want to create `with` functions this is perfect, but I fear that those who just want to use the functions can be confused.

Would you agree to make a `with_` function `#' @internal`?

**Comment by jimhester** [comment]
Ah right hadley uses `_()` to signify functions that do not do non-standard evaluation, I forgot.

`with_fun(setwd)("..", getwd())` maybe?

We can use `#' @keyword internal` if you think it will be confusing to users.

**Comment by krlmlr** [comment]
Just kidding -- this was another "point" in my argumentation.

Let's stick with an internal `with_` function. I'm currently updating the package docs and can do this in one swoop.
