### ISSUE TITLE
Tests for `with_par()`, `with_dir()`

### ISSUE THREAD

**Issue by jimhester** [jimhester/withr#15]
Neither of these files have any calls in them, so they are not counted in the coverage.

This is due to covr tracking coverage on objects defined in the package environment rather than parsing the expressions in the file directly.

Regardless we should add tests for them!

**Comment by krlmlr** [comment]
Sorry -- I guess I ditched the test for `in_dir`: 6fb64cb2b79cb

**Comment by jimhester** [comment]
No worries it is back now

**Comment by jimhester** [comment]
closed by 161e0a30b78e03dffca1a9e179d6ee82cc675e58, 4989b35a0dd15d2701ee68fbe3df5c8788f0df71
