### ISSUE TITLE
Copywrite

### ISSUE THREAD

**Issue by jimhester** [jimhester/withr#18]
So in devtools it has `person("RStudio", role = "cph")`, which assigns RStudio the copyright as both @hadley and @wch are employed by Rstudio.

While much of the code in this package was originally derived from code in devtools it has been fairly substantially reworked by @krlmlr and I.  I think we should definitely keep Hadley and Winston as authors and attribute the original source of the code to devtools, however I am not sure if RStudio should still be listed as the copyright holder as neither Kirill or I is associated with them.

If it is decided that RStudio _should_ remain the copyright holder that is fine with me, but I wanted to get some input before we submit withr to CRAN.

**Comment by hadley** [comment]
I think technically withr is a derivative work (since you did modify devtools) so rstudio should stay as copyright holder

**Comment by krlmlr** [comment]
That's fine with me.

**Comment by jimhester** [comment]
Ok thanks for the input!
