### ISSUE TITLE
Use "action" argument instead of "add"

### ISSUE THREAD

**Issue by krlmlr** [jimhester/withr#2]
- [ ] with_path
- [ ] with_libpaths
- [ ] with_temp_libpaths (#1)
- [ ] Deprecate with_lib

See https://github.com/hadley/devtools/pull/833/files#r31861098.

**Comment by jimhester** [comment]
I think it would actually be better to deprecate `with_lib` in this case.

The only place `with_lib` seems to be used in the wild (that is not simply a copy of devtools) is in `covr` (["with_lib" language:r](https://github.com/search?utf8=%E2%9C%93&q=%22with_lib%22+language%3Ar&type=Code&ref=searchresults)), whereas `with_libpaths` seems to have more use (["with_libpaths" language:r](https://github.com/search?p=1&q=%22with_libpaths%22+language%3Ar&ref=searchresults&type=Code&utf8=%E2%9C%93))

**Comment by krlmlr** [comment]
Fair enough -- updated the issues.

**Comment by krlmlr** [comment]
On the other hand, we should really discuss this:

- The new function will implement the functionality of both `with_lib` and `with_libpaths`, the default value of the `action` argument will define the, well, default action
- For `with_path`, the current default is `add = TRUE`, this should be kept (or adapted to the corresponding default value for `action`). Therefore, it seems to make sense to keep the function that has `add = TRUE` semantics by default, and this is `with_lib`
- `with_lib` is shorter
- We still can provide `with_libpaths` without the `action` argument and forward it to `with_lib`

**Comment by jimhester** [comment]
I agree it makes sense to keep the semantics the same, and having two functions for this case is inconsistent if we are using `action=` or `add=`.  You have convinced me we should go with your original proposal and just deprecate `with_libpaths`.

**Comment by krlmlr** [comment]
Should the default action for `with_path` be `"prefix"` or `"suffix"`? I think it's `"prefix"`, but this breaks compatibility. ?

**Comment by jimhester** [comment]
I think `prefix` should be the default for `with_path`, that would ensure executables in the path you are adding will be found first.

I guess if there is a time to break compatibility it is now...  We can fixup the devtools uses if needed.

**Comment by krlmlr** [comment]
Thanks. This probably means we should document all compatibility breaks.

My argument in https://github.com/jimhester/withr/issues/2#issuecomment-131098303 is moot: There's `with_envvar`, the only thing that already has an `action` argument, and the default is `"replace"`. I'm fine with keeping `with_libpaths`.

**Comment by jimhester** [comment]
BTW I added you as a collaborator on this project, so you can push directly if you want.  However feel free to open pull requests if you want me to review or discuss code.

**Comment by krlmlr** [comment]
Thanks! I just committed the two trivial changes, but I'd be glad to discuss the bigger changes via pull requests.
