### ISSUE TITLE
'defer' + 'scoped' side effects

### ISSUE THREAD

**Issue by kevinushey** [jimhester/withr#28]
The goal is to enable writing, instead of this,

``` R
with_dir(directory, {
    // code
})
```

to write this:

``` R
scoped_dir(directory)
// code
```

This can be accomplished with a couple tools. The main trick is to use `on.exit`, but attach its execution to an arbitrary parent frame. We create a function `defer` that accomplishes that:

``` R
defer <- function(expr, envir = parent.frame()) {

  # Create a call that must be evaluated in the parent frame (as
  # that's where functions and symbols need to be resolved)
  call <- substitute(
    evalq(expr, envir = envir),
    list(expr = substitute(expr), envir = parent.frame())
  )

  # Use 'do.call' with 'on.exit' to attach the evaluation to
  # the exit handlers of the selected frame
  do.call("on.exit", list(substitute(call), add = TRUE), envir = envir)

  # TODO: Not sure what we should actually return.
}
```

And then create functions that provide their 'state' and 'reset' at the exit of that scope:

``` R
scoped_dir <- function(directory) {
    owd <- setwd(directory)
    defer(setwd(owd), parent.frame())
}
```

Any thoughts on whether something like this would be appropriate for `withr`?

---

For completeness, this was inspired by the discussion here: https://stat.ethz.ch/pipermail/r-devel/2013-November/067874.html

**Comment by krlmlr** [comment]
Are you sure the do.call-on.exit pattern works? I never managed to install an on.exit handler on anything else than the function from where it was called. (I may be missing the point here completely.)

Do you have something like [RAII](https://en.wikipedia.org/wiki/Resource_Acquisition_Is_Initialization) in mind? I'm all in -- in withr or somewhere else, but I fear we might need to hack deeply into R for this.

**Comment by kevinushey** [comment]
It looks like it does to me -- I've been trying this out in packrat, I have some tests in packrat that seem to confirm it does what I expect: https://github.com/rstudio/packrat/blob/master/tests/testthat/test-utils.R#L29-L105

And you're exactly right that I wanted something like RAII :)

**Comment by krlmlr** [comment]
I like defer(), but I think it's better suited in its own package, along with helper functions that actually implement RAII. "rraii" or "defererr"?

Another thing that makes it tricky is the less-than-ideal behavior of on.exit(): with add = TRUE, new handlers are installed *after* (instead of before) existing handlers. This makes nesting complicated. One way around it would be to install a single handler (if it's not there yet; cf. sys.on.exit()) that works like a stack.

**Comment by kevinushey** [comment]
Sounds good to me! (And I agree it would make more sense for it to function like a stack; that will likely be tricky though...)

**Comment by krlmlr** [comment]
Of course I can't speak on behalf of @jimhester, and I'm sorry if it sounded as if I did. To me, RAII is a bit more generic than the scoping that "withr" provides. How about keeping defer() in "later", and accessing it to build scoping functions in "withr" style?

**Comment by jimhester** [comment]
I agree with Kirill here, I like the idea, but the usage semantics are different enough it is probably better off in its own package.

**Comment by krlmlr** [comment]
Thanks, Jim. My point is: All "with" functions are constructed by calling `with_()` which takes a setter and an optional resetter. Quite a few setters/resetters are defined in this package, this is where they belong I think. I'm suggesting a similar function `scope_()` that constructs a scoping function with the help of `later::defer()` by using the same setters/resetters. It's just that `later::defer()` can be used in a broader scope beyond `withr`, and implementing it correctly seems difficult.

**Comment by jimhester** [comment]
Makes sense to me :+1:

**Comment by hadley** [comment]
👍 👍 👍 👍 👍 👍 👍 👍

**Comment by hadley** [comment]
I don't exactly understand how defer works, but the implementation is a lot cleaner with rlang:

```R
defer <- function(expr, envir = parent.frame()) {
  expr <- enexpr(expr)

  call <- expr(
    on.exit(evalq(!!expr, envir = !!parent.frame()), add = TRUE)
  )

  eval_bare(call, envir)
}
```

**Comment by hadley** [comment]
And maybe even better to use a quosure?

```R
defer <- function(expr, envir = parent.frame()) {
  expr <- enquo(expr)
  call <- expr(on.exit(rlang::eval_tidy(!!expr), add = TRUE))
  eval_bare(call, envir)
}
```

**Comment by jimhester** [comment]
These have been in devel withr https://github.com/jimhester/withr/commit/7d1d83e7ce9638f37f3e588bce2a89b69026bbd7 for awhile actually. We can maybe move to possibly using quosures for them in a future release.
