### ISSUE TITLE
R version requirement

### ISSUE THREAD

**Issue by onlymee** [jimhester/withr#35]
Requiring R (>= 3.2.0) in the DESCRIPTION is more restrictive than devtools (currently R (>= 3.0.2)).  
Is that really necessary?

**Comment by jimhester** [comment]
Probably not necessary, but in I have not tested withr against that version. If you do so and run the tests without issue I can reduce it.

**Comment by carloscinelli** [comment]
The current requirement makes `covr` fail with r-builder old-rel: 
 https://travis-ci.org/carloscinelli/benford.analysis/jobs/103106861

**Comment by carloscinelli** [comment]
Related problem: https://github.com/hadley/devtools/issues/1047
