### ISSUE TITLE
R 3.1 support

### ISSUE THREAD

**Issue by jeroenooms** [jimhester/withr#39]
It's a bit unfortunate that the latest version of devtools no longer works on R 3.1.x. Is there a way we can make `withr` work on R 3.1, at least until R 3.3 is out?

**Comment by jimhester** [comment]
Yep this is the same ashttps://github.com/jimhester/withr/issues/35, I just need to release the devel version on CRAN.

**Comment by jeroenooms** [comment]
Sorry for being pushy but could you try to do that pretty soonish? The new version of devtools was released over a week ago and everything that depends on devtools is now failing to build on 3.1 systems.

**Comment by jeroenooms** [comment]
Thanks

**Comment by jimhester** [comment]
Thanks for closing, sorry I forgot to update this after I submitted to CRAN yesterday.
