### ISSUE TITLE
with_makevars()

### ISSUE THREAD

**Issue by krlmlr** [jimhester/withr#42]
The `.R/Makevars` is useful for setting compile flags; setting them temporarily is a pain.

To avoid overwriting an existing file, we could

1. create `/tmp/home-xxxx` and there create a symlink for everything in `$HOME` except `.R/Makevars`
1. create `/tmp/home-xxxx/.R/Makevars`, with an optional `-include /old/home/.R/Makevars`
1. set the `HOME` environment variable to `/tmp/home-xxxx`
1. run the code
1. undo everything

CC @gaborcsardi

**Comment by jimhester** [comment]
I am confused, `with_makevars()` already exists (https://github.com/jimhester/withr/blob/master/R/makevars.R)

**Comment by krlmlr** [comment]
My bad, didn't look. The method I outlined would restrict the modification to the current R session (as opposed to the current code which seems to modify the file globally), but might not work on Windows.

**Comment by jimhester** [comment]
The current code creates a new file and sets R_MAKEVARS_USER, it doesn't touch the existing file.

**Comment by krlmlr** [comment]
Thanks for clarifying.
