### ISSUE TITLE
Split docs, one help page per function

### ISSUE THREAD

**Issue by krlmlr** [jimhester/withr#9]
This was a no-go for devtools, but I think in this package it would be better. The list of all functions is the package index. ?

**Comment by jimhester** [comment]
Agreed, I was planning on doing this as well before release.

**Comment by krlmlr** [comment]
Great, let's do this after merging #8 but before #1. I can do this, but please go ahead if you like to. Probably no other work on the code should be done during this transition.

**Comment by jimhester** [comment]
Realized this issue was just for the help pages, but I split the functions into separate files as well.

I was getting some strange roxygen behavior that was requiring me to use explicit `@title` declarations on some of the functions, but not others.  I am not sure what was going on...

**Comment by krlmlr** [comment]
I also thought about splitting the source. Looks good, just a few notes:

1. Should we define a `#' @family with` ?
2. I'm not sure we need `?withr` -- the package index serves almost the same purpose, and maintaining it is extra effort
3. Do we export `get_path` and the other getters/setters? The `# @rdname` for `get_path` misses an apostrophe
4. The titles and descriptions of the individual `with_` functions still seem to need some love
5. I like the expressive style of the help of, e.g., [BatchJobs](http://www.rdocumentation.org/packages/BatchJobs/functions/makeRegistry) -- the type of each argument is mentioned explicitly. Is this something you would consider adopting?
6. Do we want to keep `in_dir`?

I can take care of some of the above, please let me know which.

**Comment by jimhester** [comment]
1. I thought of that, but then decided basically all the functions in the package will be in there, so not sure how useful it is.
2. `?withr`, agreed on the redundancy, it was mostly a place to define `new` and `code` arguments.  If you think it is better to remove it I am fine with it.
3. I would say no, I think get_path being exported was a holdover from devtools.
4. Agreed, feel free to improve them!
5. I like it as well, we can use that format.  I was planning on using https://github.com/gaborcsardi/argufy to explicitly check arguments once it is fleshed out a little more and on CRAN.
6. devtools only has `in_dir`, but it is the only function that deviates from `with_*`, so we can remove it, I don't think the questionable improved readability is worth it.

Feel free to do any/all of the above if you have time, I can tackle what you don't get to tomorrow.

**Comment by krlmlr** [comment]
1. is a cheap way to add links to all other functions
2. How about defining `new` and `code` in one of the functions and inheriting from there? Perhaps we should keep the examples in `?withr`, it's a good entry point. I'll try to find a compromise
3. ok
4. I can do that, but not today
5. Sounds good. Let's leave argument checking for now, just document the expected types.
6. ok
